# version: '3.8'
# services:
#   db:
#     image: mysql:8.0
#     cap_add:
#       - SYS_NICE
#     restart: always
#     environment:
#       - MYSQL_DATABASE=webshop
#       - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
#     ports:
#       - '3306:3306'
#     volumes:
#       - db:/var/lib/mysql
#       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
# volumes:
#   db:
#     driver: local


version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'webshop'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
# Names our volume
volumes:
  db:
    driver: local